#pragma once
#include "I18nKeys.h"

// THIS FILE IS AUTO-GENERATED BY gen_i18n.py. DO NOT EDIT.
// clang-format off

namespace i18n_strings {

extern const char STRINGS_EN_DATA[];
extern const uint16_t OFFSETS_EN[];
extern const char STRINGS_RU_DATA[];
extern const uint16_t OFFSETS_RU[];
extern const char STRINGS_UK_DATA[];
extern const uint16_t OFFSETS_UK[];

}  // namespace i18n_strings
